// Generated by frontend/scripts/make-icons.py -- do not edit by hand.
// The geometry lives in that script so the SVG, the PNGs and this file
// cannot drift apart.
export interface LogoFace {
  d: string;
  fill: string;
}

export const LOGO_FACES: LogoFace[] = [
  { d: "M10 18.7 21 12.35 32 18.7 21 25.05Z", fill: "#9DBEFF" },
  { d: "M21 12.35 32 6 43 12.35 32 18.7Z", fill: "#B8D0FF" },
  { d: "M32 18.7 43 12.35 54 18.7 43 25.05Z", fill: "#7FD8F5" },
  { d: "M21 25.05 32 18.7 43 25.05 32 31.4Z", fill: "#8CB0FF" },
  { d: "M10 18.7 21 25.05 21 38.35 10 32Z", fill: "#5B96FF" },
  { d: "M21 25.05 32 31.4 32 44.7 21 38.35Z", fill: "#4D8DFF" },
  { d: "M21 38.35 32 44.7 32 58 21 51.65Z", fill: "#3F82F7" },
  { d: "M10 32 21 38.35 21 51.65 10 45.3Z", fill: "#6BA0FF" },
  { d: "M32 31.4 43 25.05 43 38.35 32 44.7Z", fill: "#2F62EE" },
  { d: "M43 25.05 54 18.7 54 32 43 38.35Z", fill: "#2454E6" },
  { d: "M43 38.35 54 32 54 45.3 43 51.65Z", fill: "#7B5BF0" },
  { d: "M32 44.7 43 38.35 43 51.65 32 58Z", fill: "#1E49D2" },
];
